"""
CLI utility functions for Physics Equation Explainer and Analysis
"""

import textwrap
from pathlib import Path
from rich.console import Console
from rich.panel import Panel
from rich.text import Text

console = Console()


def print_header(text: str, subtitle: str = ""):
    """Print main header with minimal spacing"""
    panel = Panel(
        Text(text, justify="center", style="bold green"),
        title="[bold]MathEqs[/bold]",
        subtitle=subtitle,
        border_style="blue",
    )
    console.print(panel)


def print_section(title: str, content: str, max_width: int = 70):
    """Print formatted section with consistent spacing"""
    panel = Panel(
        Text(content, justify="left"),
        title=f"[bold cyan]{title}[/bold cyan]",
        border_style="cyan",
    )
    console.print(panel)


def print_subsection(title: str, content: str, max_width: int = 70):
    """Print subsection with smaller emphasis"""
    console.print(f"[bold yellow]• {title}[/bold yellow]")
    wrapped = textwrap.fill(content, width=max_width, subsequent_indent="  ")
    console.print(f"  {wrapped}")


def print_list(title: str, items: list, indent: int = 2):
    """Print formatted list with consistent spacing"""
    print(f"\n{title}")
    for item in items:
        print(f"{' ' * indent}• {item}")


def generate_markdown_document(title: str, equation: str, content_dict: dict) -> str:
    """Generate a complete Markdown document"""
    markdown = f"""# {title}

**Generated by:** MathEqs - Physics Equation Explainer

---

## Equation

$$
{equation}
$$

"""

    for section_title, content in content_dict.items():
        markdown += f"## {section_title}\n\n"
        markdown += content + "\n\n"

    return markdown.strip()


def generate_four_section_markdown(
    equation_name: str,
    equation: str,
    introduction: str = "",
    history: str = "",
    derivation: str = "",
    applications: str = "",
) -> str:
    """Generate Markdown with four main sections: Introduction, History, Derivation, Applications"""
    markdown = f"""# {equation_name}

**Generated by:** MathEqs - Physics Equation Explainer

---

## Equation

$$
{equation}
$$

"""

    sections = [
        ("Introduction", introduction),
        ("History", history),
        ("Derivation", derivation),
        ("Applications", applications),
    ]

    for section_title, content in sections:
        if content and content.strip():
            markdown += f"## {section_title}\n\n"
            markdown += content.strip() + "\n\n"

    return markdown.strip()


def save_markdown_file(content: str, filename: str) -> str:
    """Save Markdown content to a .md file"""
    filepath = Path(filename)
    if not filepath.suffix:
        filepath = filepath.with_suffix(".md")

    filepath.write_text(content, encoding="utf-8")
    return str(filepath.absolute())


def print_error(message: str):
    """Print an error message to the console"""
    console.print(
        Panel(
            Text(message, justify="center"),
            title="[bold red]Error[/bold red]",
            border_style="red",
        )
    )
