"""
CLI utility functions for Physics Equation Explainer and Analysis
"""

import logging
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.text import Text

logger = logging.getLogger(__name__)

console = Console()


def print_header(text: str, subtitle: str = "") -> None:
    panel = Panel(
        Text(text, justify="center", style="bold green"),
        title="[bold]MathEqs[/bold]",
        subtitle=subtitle,
        border_style="blue",
    )
    console.print(panel)


def print_section(title: str, content: str) -> None:
    panel = Panel(
        Text(content, justify="left"),
        title=f"[bold cyan]{title}[/bold cyan]",
        border_style="cyan",
    )
    console.print(panel)


def print_subsection(title: str, content: str) -> None:
    console.print(f"[bold yellow]• {title}[/bold yellow]")
    console.print(f"  {content}")


def print_list(title: str, items: list[str], indent: int = 2) -> None:
    console.print(f"\n{title}")
    for item in items:
        console.print(f"{' ' * indent}• {item}")


def generate_markdown_document(title: str, equation: str, content_dict: dict[str, str]) -> str:
    markdown = f"""# {title}

**Generated by:** MathEqs - Physics Equation Explainer

---

## Equation

$$
{equation}
$$

"""
    for section_title, content in content_dict.items():
        markdown += f"## {section_title}\n\n"
        markdown += content + "\n\n"
    return markdown.strip()


def generate_four_section_markdown(
    equation_name: str,
    equation: str,
    introduction: str = "",
    history: str = "",
    derivation: str = "",
    applications: str = "",
) -> str:
    markdown = f"""# {equation_name}

**Generated by:** MathEqs - Physics Equation Explainer

---

## Equation

$$
{equation}
$$

"""
    sections = [
        ("Introduction", introduction),
        ("History", history),
        ("Derivation", derivation),
        ("Applications", applications),
    ]
    for section_title, content in sections:
        if content and content.strip():
            markdown += f"## {section_title}\n\n"
            markdown += content.strip() + "\n\n"
    return markdown.strip()


def save_markdown_file(content: str, filename: str) -> str:
    filepath = Path(filename)
    if not filepath.suffix:
        filepath = filepath.with_suffix(".md")
    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text(content, encoding="utf-8")
    logger.info("Saved markdown to %s", filepath)
    return str(filepath.absolute())


def print_error(message: str) -> None:
    console.print(
        Panel(
            Text(message, justify="center"),
            title="[bold red]Error[/bold red]",
            border_style="red",
        )
    )
